source("make_parameters.R")
source("get_R0.R")
source("apply_links.R")
source("apply_setup.R")
source("make_pedigree.R")
source("make_grm.R")
source("make_traits_from_grm.R")
source("make_traits_from_pedigree.R")
source("set_groups.R")
source("apply_fixed_effects.R")
source("simulate_epidemic.R")
source("init_populations.R")
# source("discretise.R")
source("prepare_data.R")
source("generate_sire20_xml.R")
source("generate_sire21_xml.R")
source("generate_sire22_xml.R")
source("make_time_series.R")
source("make_plots.R")
source("get_ranks.R")
source("utils.R")

